### ISSUE TITLE
build

### ISSUE THREAD

**Issue by charlieroberts** [bandaloo/post5#1]
I know it's "bad  form" to include a build in the repo... but I think it makes sense for a library like this, so that beginning users (common to p5!) could pull in post5.js from a CDN like jsdelivr or whatever without having to mess with the command line. 

On a personal note, I was just looking to quickly pull this into gibber via CDN so I could share via link instead of needing to include the file somewhere.

**Comment by charlieroberts** [comment]
ping

**Comment by bandaloo** [comment]
yeah i think it's a pragmatic thing to do to just include the minified file

**Comment by bandaloo** [comment]
added post5.js which is accessible via script tag with https://cdn.jsdelivr.net/gh/bandaloo/post5@main/post5.js
